Intro:
  pages:
    intro/preface: "Preface"

Protocol:
  pages:
    protocol/actions: "Actions"
    protocol/assets: "Assets"
    protocol/messages: "Messages"
    protocol/field-types: "Field Types"

Concepts:
  pages:
    concepts/contracts: "Contracts"
    concepts/transactions: "Transactions"
    concepts/operations: "Operations"
    concepts/rules: "Rules"
    concepts/tokens: "Tokens"
    concepts/asset-management: "Assets"
    concepts/asset-transfers: "Transfers"
    concepts/governance: "Governance"
    concepts/enforcement: "Enforcement"
    concepts/authorization-flags: "Authorization Flags"
    concepts/oracles: "Oracles"
    concepts/registers: "Registers"
    concepts/messaging: "Messaging"

Examples:
  pages:
    example/family-trust: "Family Trust"
    example/air-miles: "Air Miles"
    example/movie-tickets: "Movie Tickets"
