Intro:
  pages:
    intro/preface: "Preface"

Protocol:
  pages:
    protocol/actions: "Actions"
    protocol/assets: "Assets"
    protocol/messages: "Messages"
    protocol/field-types: "Field Types"

Concepts:
  pages:
    # concepts/action-mechanism: "Action Mechanism"
    concepts/contracts: "Contract Types"
    concepts/transactions: "Transactions"
    concepts/operations: "Tokenized Operations"
    concepts/rules: "Rules"
    concepts/tokens: "Tokens"
    concepts/assets: "Creating and managing assets"
    concepts/transfers: "Transferring assets"
    concepts/governance: "Contract and asset governance"
    concepts/enforcement: "Tokenized enforcement actions"
    concepts/message-types: "Message type Overview"
    concepts/oracles: "Tokenized oracles"
    concepts/asset-types: "Asset Type Overview"

Examples:
  pages:
    example/family-trust: "Family Trust"
    example/air-miles: "Air Miles"
    example/movie-tickets: "Movie Tickets"
