Intro:
  pages:
    intro/preface: "Preface"
    intro/philosophy: "Philosophy"

Concepts:
  pages:
    concepts/contracts: "Contracts"
    concepts/transactions: "Transactions"
    concepts/operations: "Operations"
    concepts/rules: "Rules"
    concepts/tokens: "Tokens"
    concepts/asset-management: "Asset Management"
    concepts/asset-transfers: "Asset Transfers"
    concepts/governance: "Governance"
    concepts/enforcement: "Enforcement"
    concepts/permissions: "Permissions"
    concepts/oracles: "Oracles"
    concepts/registers: "Registers"
    concepts/messaging: "Messaging"

Specification:
  pages:
    protocol/intro: "Introduction"
    protocol/actions: "Actions"
    protocol/assets: "Assets"
    protocol/messages: "Messages"
    protocol/resources: "Resources"

Examples:
  pages:
    example/frequent-flyer-points: "Frequent Flyer"
    example/movie-tickets: "Movie Tickets"
