Intro:
  pages:
    intro/preface: "Preface"
Main Concepts:
  pages:
    main-concepts/action-mechanism: "Action Mechanism"
    main-concepts/contracts: "Contracts"
    main-concepts/transactions: "Transactions"
    main-concepts/operations: "Tokenized Operations"
    main-concepts/rules: "Rules"
    main-concepts/tokens: "Tokens"
    main-concepts/assets: "Creating and managing assets"
    main-concepts/governance: "Contract and asset governance"
    main-concepts/enforcement: "Tokenized enforcement actions"
    main-concepts/message-types: "Message type Overview"
    main-concepts/registries: "Tokenized registries"
    main-concepts/asset-types: "Asset Type Overview"
Examples:
  pages:
    example/bill-family-trust: "Bill's family trust"
    example/bob-gives-away-air-miles: "Bob's air miles"
    example/alice-goes-to-the-movies: "Alice goes to the movies"
Message:
  pages:
    message/publid-message: "Public Messages"
    message/private-message: "Private Messages"
    message/offer: "Offer Message"
    message/signature-reqest: "Signature Request message"
Actions:
  pages:
    action/contract-offer: "Contract Offer"
    action/contract-formation: "Contract Formation"
    action/contract-amendment: "Contract Amendment"
    action/static-contract-formation: "Static Contract Formation"
    action/asset-definition: "Asset Definition"
    action/asset-creation: "Asset Creation"
    action/asset-modification: "Asset Modification"
    action/transfer: "Transfer"
    action/settlement: "Settlement"
    action/initiative: "Initiative"
    action/referendum: "Referendum"
    action/vote: "Vote"
    action/ballot-cast: "Ballot Cast"
    action/ballot-counted: "Ballot Counted"
    action/result: "Result"
    action/order: "Order"
    action/freeze: "Freeze"
    action/thaw: "Thaw"
    action/confiscation: "Confiscation"
    action/reconciliation: "Reconciliation"
    action/establishment: "Establishment"
    action/addition: "Addition"
    action/alteration: "Alteration"
    action/removal: "Removal"
    action/message: "Message"
    action/rejection: "Rejection"
Asset Types:
  pages:
    asset/coupon: "Coupons"
    asset/loyalty-points: "Loyalty Points"
    asset/membership: "Membership"
    asset/share-common: "Common Share"
    asset/ticket-admission: "Admission Ticket"
    asset/currency: "Currency"
